# Generated by Django 4.2.7 on 2024-01-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20)),
                ('task_desc', models.TextField()),
                ('date_added', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
